{% extends '../../project/templates/default/default.html.swig' %}{% block content %}
<p>
After satisfying all your unconscious desires the next target is your mind, the collective conscious.
</p>

<p>
More and more products will satisfy your desire to know yourself, people around you and the entire world.
</p>

<p>
Now you’ll pay for what your attention goes for. You’ll pay to avoid loneliness.
</p>
{% endblock %}