{% extends '../../project/templates/default/default.html.swig' %}{% block content %}
<p>
The most boring lifeline belongs to politicians and whom they rule.
<br/>
Second are engineers with a constant march to the unwanted.
<br/>
The best might be for entrepreneurs or whoever goes for the ride.
</p>

<p class="notice">
Check the images <a href="http://matt.might.net/articles/problem-shapes/">here</a>
</p>
{% endblock %}