{% extends '../../project/templates/default/default.html.swig' %}{% block content %}
<p>
Time is the most valuable non-renewable, infinite resource our world has.
</p>
<p>
Attention is when a portion of time is taken by an individual.
</p>
<p>
Attention transforms time into energy. If you spend it admiring Tom Cruise you will become less and he will become more.
</p>
<p>
Reality is built on the energies of people spending attention.
</p>
{% endblock %}