{% extends '../../project/templates/default/default.html.swig' %}{% block content %}
<p>
It’s not easy to describe
{% set image = people[0] %} {% include '../../project/card/card.html.swig' %}
<p>&mdash; to summarise his heritage to the world. But one thing is sure: he was a visionary strategist and a
scholar spanning over multiple fields of science.
</p>

<p>
He wrote about future half century ago. It is easy <em>now</em> to decide how serious we should take his predictions.
</p>


<h2>Basics</h2>

<p>
The world is changing faster than we can imagine.
</p>

<p>
The moral canon has completely disappeared, there are no more <p><blockquote>Taboos</blockquote><p>and moral considerations about what
we should do, and how we should do.
</p>

<p>
We live in the era of total freedom, whatever this means.
</p>


<h2>Politics</h2>

<p>
The world is over hyped due to cold war. From this grandiosity we should step back to earth.
</p>

<p>
Asymmetry is the new world order: small is taking over huge, and in the same time huge is getting bigger by taking over smaller.
</p>

<p>
Masses are taking control over their lives of consumption,
polls and rating rules media & politics.
</p>
<p>
Politics takes over masses through control of freedom:
tight security, no more human rights.
</p>


<h2>Culture</h2>

<p>
This is the end of the high culture. Only pop culture matters.
</p>

<p>
There is full freedom, there are no more moral obstacles and considerations. Sensational is the basic value without any morals.
</p>
<p>
The overall presence of information overflow, the logorrhea of information introduces anarchy.
</p>
<p>
Creative people are crazy, schizophrenic, absurd, and shocking without having enough lived experiences to serve as background for
really valuable creations.
</p>
<p>
In arts the next paradigm is reincarnational postmodernims: I’ll reborn to destroy more.
</p>


<h2>Civil Society</h2>

<p>
Emotional over rational.
</p>
<p>
Earth is overpopulated and resources are running out.
</p>
<p>
It is very common the Bad wins and the Good is always a looser. No more Tom & Jerry.
</p>
<p>
Is driven completely by the media.
</p>

<h2>Science & Technology</h2>

<p>
<strong>Energy</strong> &mdash; Oil and uranium is running out; we might have luck with the revisited cold fusion.
</p>
<p>
<strong>Nature</strong> &mdash; Despite any technological advancement we are always vulnerable by supreme forces.
</p>
<p>
<strong>Speed</strong> &mdash; Using the words of Paul Virilio, we are living </p><blockquote>The aesthetics of disappearance.</blockquote>
<p>
<strong>Universe</strong> &mdash; Is just an illusion: an illegal loan with no cover. The Cosmos exists on an unlimited credit.
</p>
<p>
<strong>Evolution</strong> &mdash; Is non-linear but random.
</p>
<p>
<strong>Scientists</strong> &mdash; There are lots of magicians and charlatans
masked scientists; there are no more polymaths;
the space of inventions is limited for a person, we are repeating themselves independently from others —
everything will become a pseudo-plagiarism.
</p>
<p>
<strong>God and Illumination</strong> &mdash; We have a system (the limbic system in the human brain) relating ourselves to the Everything;
illumination is based on admiration and respect, it is Dostoevsky’s </p><blockquote>Touch of God,</blockquote><p>
reachable during meditating yourself into deep silence, or using hallucinogenic drugs.
However all these can be bought using Prof. Persinger’s Transcanial Simulator.
</p>
<p>
<strong>Genesis</strong> &mdash; Procreation and extinction are strongly related. Any cosmic holocaust is followed by biological
innovation/evolution of life.
</p>
<p>
<strong>Artificial Intelligence</strong> &mdash; The border between natural and artificial will disappear.
There will be an electronic brain and soul not distinguishable from the original.
</p>

<h2>Information and Communication Technology</h2>

<p>
The Information Market is crucial for capital and corporations.
</p>
<p>
Information becomes genital, fully sexualised:</p>
<blockquote>Everything that would serve humanity turned to be a strangehold of restrictions.</blockquote>
<p>
Ubiquity is exponential power.
</p>
<p>
It is more difficult to distinct truth from fake. Information leads to paranoia.
</p>
<p>
Internet has a Marxist / Communist aspect: information & knowledge as individual property goes to service providers, corporations.
</p>
<p>
The American Dream is replaced by Virtual Reality.
</p>

<h2>Biotechnology, Genetics</h2>

<p>
The strapline is </p><blockquote>You can do better than nature (James Young of MedImmune)</blockquote><p> which leads to autoevolution.
</p>
<p>
Genetics is a pure market product.
In 10 years no one can recognise a genetically pimped sportsman.
Molecular and quantum biology to watch.
</p>
<p>
Patenting human genes reintroduces slavery.
</p>
<p>
Humans are nothing without culture — and nobody takes into consideration the cultural aspect of cloning humans.
</p>
<p>
Homo sapiens is the latest specie of the natural evolution.
We are the latest reliquiae of the uncivilised nature.
</p>

{% endblock %}
